/* LP-LEGAL-02 — first-party contact delivery through the BCSentinel backend. */
(function(){
  let activeContent=null;
  function locale(){return document.documentElement.lang==='en'?'en':'de'}
  function endpoint(){
    const configured=window.BCSENTINEL_API_BASE_URL||document.querySelector('meta[name="bcsentinel-api-base-url"]')?.content||'';
    const local=/^(localhost|127\.0\.0\.1)$/.test(location.hostname)?'http://localhost:8000':'';
    return new URL('/public/contact',configured||local||location.origin).toString();
  }
  function optionMarkup(items){return items.map(x=>`<option value="${x.value}">${x.label}</option>`).join('')}
  function markup(t){return `<div class="contact-page"><div class="contact-container"><section class="contact-hero"><div><p class="contact-eyebrow">${t.eyebrow}</p><h1>${t.title}</h1><p class="contact-lead">${t.lead}</p></div><aside class="contact-hero-aside" aria-label="${t.asideAria}">${t.promises.map(x=>`<div class="contact-promise"><strong>${x.title}</strong><p>${x.text}</p></div>`).join('')}</aside></section><section class="contact-grid"><article class="contact-card"><h2>${t.formTitle}</h2><p class="contact-note">${t.formNote}</p><form id="contactForm" class="contact-form" novalidate aria-label="${t.formAria}"><div class="contact-honeypot" aria-hidden="true"><label for="website">Website</label><input id="website" name="website" type="text" tabindex="-1" autocomplete="off"></div><div class="contact-field-row"><label class="contact-field"><span>${t.fields.name}</span><input id="name" name="name" type="text" minlength="2" maxlength="120" required placeholder="${t.placeholders.name}"></label><label class="contact-field"><span>${t.fields.email}</span><input id="email" name="email" type="email" maxlength="254" required placeholder="${t.placeholders.email}"></label></div><div class="contact-field-row"><label class="contact-field"><span>${t.fields.company}</span><input id="company" name="company" type="text" maxlength="160" placeholder="${t.placeholders.company}"></label><label class="contact-field"><span>${t.fields.topic}</span><select id="topic" name="topic">${optionMarkup(t.topics)}</select></label></div><label class="contact-field"><span>${t.fields.message}</span><textarea id="message" name="message" minlength="10" maxlength="5000" required placeholder="${t.placeholders.message}"></textarea></label><label class="contact-field"><span>${t.fields.privacy}</span><span class="contact-consent"><input id="privacyConsent" name="privacyConsent" type="checkbox" required><span>${t.privacyText} <a href="privacy.html">${t.privacyLink}</a></span></span></label><div id="formStatus" class="contact-status" role="status" aria-live="polite"></div><button id="submitBtn" class="contact-submit" type="submit">${t.submit}</button></form></article><aside class="contact-card"><h2>${t.asideTitle}</h2><p class="contact-note">${t.directText}</p><div class="contact-side-list"><div class="contact-side-item"><strong>${t.emailLabel}</strong><p><a href="mailto:support@bcsentinel.com">support@bcsentinel.com</a></p></div><div class="contact-side-item"><strong>${t.topicsLabel}</strong><p>${t.topicsText}</p></div></div><div class="contact-security-note">${t.securityNote}</div></aside></section></div></div>`}
  function applyMeta(t){document.title=t.metaTitle;const m=document.querySelector('meta[name="description"]');if(m)m.content=t.metaDescription}
  function preselectTopic(){const requested=new URLSearchParams(location.search).get('product');const select=document.getElementById('topic');if(!requested||!select)return;const map={assessment:'Pricing',validation:'Pricing',monitoring:'Pricing',partner:'Partner',support:'Support',pilot:'Pilot'};select.value=map[requested]||select.value}
  function showStatus(type,message){const box=document.getElementById('formStatus');if(!box)return;box.className=`contact-status show ${type}`;box.textContent=message}
  function bindForm(t){const form=document.getElementById('contactForm');const submit=document.getElementById('submitBtn');if(!form||!submit)return;form.addEventListener('submit',async(event)=>{event.preventDefault();if(!form.checkValidity()){showStatus('error',t.status.invalid);form.reportValidity();return}submit.disabled=true;submit.textContent=t.submitting;const status=document.getElementById('formStatus');if(status){status.className='contact-status';status.textContent=''}const data=new FormData(form);const payload={name:data.get('name'),email:data.get('email'),company:data.get('company')||null,topic:data.get('topic')||'General',message:data.get('message'),locale:locale(),website:data.get('website')||null};try{const response=await fetch(endpoint(),{method:'POST',headers:{Accept:'application/json','Content-Type':'application/json'},body:JSON.stringify(payload)});if(!response.ok)throw new Error(`submission failed: ${response.status}`);const result=await response.json();if(!result?.accepted)throw new Error('unexpected response');form.reset();showStatus('success',t.status.success)}catch(_){showStatus('error',t.status.error)}finally{submit.disabled=false;submit.textContent=t.submit}})}
  async function render(){if(!window.BCSentinelContent)return;const payload=await window.BCSentinelContent.loadBundle('contact',locale());const t=payload?.page;if(!t)return;activeContent=t;applyMeta(t);const root=document.getElementById('contactPageRoot');if(!root)return;root.innerHTML=markup(t);preselectTopic();bindForm(t)}
  function init(){render().catch(()=>{});new MutationObserver(m=>{if(m.some(x=>x.attributeName==='lang'))render().catch(()=>{})}).observe(document.documentElement,{attributes:true,attributeFilter:['lang']})}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();
