/* LP-GL-11A — translated contact page while preserving submission behavior. */
(function(){
  const FORM_ENDPOINT='https://formsubmit.co/ajax/support@bcsentinel.com';
  let activeContent=null;
  function locale(){return document.documentElement.lang==='en'?'en':'de'}
  function optionMarkup(items){return items.map(x=>`<option value="${x.value}">${x.label}</option>`).join('')}
  function markup(t){return `<div class="contact-page"><div class="contact-container"><section class="contact-hero"><div><p class="contact-eyebrow">${t.eyebrow}</p><h1>${t.title}</h1><p class="contact-lead">${t.lead}</p></div><aside class="contact-hero-aside" aria-label="${t.asideAria}">${t.promises.map(x=>`<div class="contact-promise"><strong>${x.title}</strong><p>${x.text}</p></div>`).join('')}</aside></section><section class="contact-grid"><article class="contact-card"><h2>${t.formTitle}</h2><p class="contact-note">${t.formNote}</p><form id="contactForm" class="contact-form" novalidate aria-label="${t.formAria}"><input type="hidden" name="_subject" value="BCSentinel Contact Request"><input type="hidden" name="_template" value="table"><input type="hidden" name="_url" value="https://www.bcsentinel.com/contact.html"><input type="hidden" name="_replyto" id="replyToMirror" value=""><input type="hidden" name="_blacklist" value="http://,https://,viagra,casino,crypto,loan,porn,seo service,backlink"><div class="contact-honeypot" aria-hidden="true"><label for="website">Website</label><input id="website" name="_honey" type="text" tabindex="-1" autocomplete="off"></div><div class="contact-field-row"><label class="contact-field"><span>${t.fields.name}</span><input id="name" name="name" type="text" required placeholder="${t.placeholders.name}"></label><label class="contact-field"><span>${t.fields.email}</span><input id="email" name="email" type="email" required placeholder="${t.placeholders.email}"></label></div><div class="contact-field-row"><label class="contact-field"><span>${t.fields.company}</span><input id="company" name="company" type="text" placeholder="${t.placeholders.company}"></label><label class="contact-field"><span>${t.fields.topic}</span><select id="topic" name="topic">${optionMarkup(t.topics)}</select></label></div><label class="contact-field"><span>${t.fields.message}</span><textarea id="message" name="message" required placeholder="${t.placeholders.message}"></textarea></label><label class="contact-field"><span>${t.fields.privacy}</span><span class="contact-consent"><input id="privacyConsent" name="privacyConsent" type="checkbox" required><span>${t.privacyText} <a href="privacy.html">${t.privacyLink}</a></span></span></label><div id="formStatus" class="contact-status" role="status" aria-live="polite"></div><button id="submitBtn" class="contact-submit" type="submit">${t.submit}</button></form></article><aside class="contact-card"><h2>${t.asideTitle}</h2><p class="contact-note">${t.directText}</p><div class="contact-side-list"><div class="contact-side-item"><strong>${t.emailLabel}</strong><p><a href="mailto:support@bcsentinel.com">support@bcsentinel.com</a></p></div><div class="contact-side-item"><strong>${t.topicsLabel}</strong><p>${t.topicsText}</p></div></div><div class="contact-security-note">${t.securityNote}</div></aside></section></div></div>`}
  function applyMeta(t){document.title=t.metaTitle;const m=document.querySelector('meta[name="description"]');if(m)m.content=t.metaDescription}
  function preselectTopic(){const requested=new URLSearchParams(location.search).get('product');const select=document.getElementById('topic');if(!requested||!select)return;const map={assessment:'Pricing',validation:'Pricing',monitoring:'Pricing',partner:'Partner',support:'Support',pilot:'Pilot'};select.value=map[requested]||select.value}
  function showStatus(type,message){const box=document.getElementById('formStatus');if(!box)return;box.className=`contact-status show ${type}`;box.textContent=message}
  function bindForm(t){const form=document.getElementById('contactForm');const email=document.getElementById('email');const mirror=document.getElementById('replyToMirror');const submit=document.getElementById('submitBtn');if(!form||!email||!mirror||!submit)return;email.addEventListener('input',()=>{mirror.value=email.value});form.addEventListener('submit',async(event)=>{event.preventDefault();if(!form.checkValidity()){showStatus('error',t.status.invalid);form.reportValidity();return}submit.disabled=true;submit.textContent=t.submitting;mirror.value=email.value;const status=document.getElementById('formStatus');if(status){status.className='contact-status';status.textContent=''}try{const response=await fetch(FORM_ENDPOINT,{method:'POST',body:new FormData(form),headers:{Accept:'application/json'}});if(!response.ok)throw new Error('submission failed');const result=await response.json();if(!(result&&(result.success===true||result.success==='true'||result.message)))throw new Error('unexpected response');form.reset();mirror.value='';showStatus('success',t.status.success)}catch(_){showStatus('error',t.status.error)}finally{submit.disabled=false;submit.textContent=t.submit}})}
  async function render(){if(!window.BCSentinelContent)return;const payload=await window.BCSentinelContent.loadBundle('contact',locale());const t=payload?.page;if(!t)return;activeContent=t;applyMeta(t);const root=document.getElementById('contactPageRoot');if(!root)return;root.innerHTML=markup(t);preselectTopic();bindForm(t)}
  function init(){render().catch(()=>{});new MutationObserver(m=>{if(m.some(x=>x.attributeName==='lang'))render().catch(()=>{})}).observe(document.documentElement,{attributes:true,attributeFilter:['lang']})}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();
