/* LP-GL-06 — Product Proof */
(function(){
const copy={
de:{findEyebrow:'Product Proof',findTitle:'Von einem technischen Finding zur priorisierten Handlung.',findLead:'BCSentinel verbindet Severity, betroffene Datensätze, Estimated Loss und konkrete Empfehlungen in einer nachvollziehbaren Entscheidungssicht.',detailTitle:'Doppelte Kreditoren-Bankverbindungen',detailText:'Mehrere Kreditoren verwenden identische Bankverbindungen. Das erhöht Kontrollaufwand und Risiko im Zahlungsprozess.',affected:'Betroffene Datensätze',impact:'Estimated Loss',status:'Status',open:'Offen',recommend:'Empfohlene Maßnahme',recommendText:'Bankverbindungen prüfen, Dubletten konsolidieren und dokumentierte Ausnahmen gezielt kennzeichnen.',method:'Berechnungsmethodik ansehen →',reportEyebrow:'Executive Reporting',reportTitle:'Ein Report, den Management tatsächlich verwenden kann.',reportLead:'Der Executive Report übersetzt Scanergebnisse in Score, geschäftliche Auswirkungen, Prioritäten und nächste Schritte – ohne technische Rohdaten zu überfrachten.',reportChecks:['Managementgerechte Zusammenfassung','Health Score und Severity-Verteilung','Estimated Loss und Potential Saving','Priorisierte Maßnahmen und nächste Schritte'],dashboardEyebrow:'Dashboard Preview',dashboardTitle:'Eine zentrale Sicht auf Zustand, Risiken und Fortschritt.',dashboardLead:'Overview, Findings und Monitoring greifen ineinander, damit Teams nicht nur Probleme sehen, sondern deren Entwicklung und Bearbeitungsstatus verfolgen können.',sample:'Repräsentative Produktvorschau mit Beispieldaten.'},
en:{findEyebrow:'Product Proof',findTitle:'From a technical finding to prioritized action.',findLead:'BCSentinel connects severity, affected records, Estimated Loss, and concrete recommendations in one defensible decision view.',detailTitle:'Duplicate vendor bank accounts',detailText:'Multiple vendors use identical bank details. This increases control effort and risk in the payment process.',affected:'Affected records',impact:'Estimated Loss',status:'Status',open:'Open',recommend:'Recommended action',recommendText:'Review bank details, consolidate duplicates, and mark documented exceptions where appropriate.',method:'View calculation methodology →',reportEyebrow:'Executive Reporting',reportTitle:'A report management can actually use.',reportLead:'The Executive Report translates scan results into score, business impact, priorities, and next steps without overwhelming readers with technical raw data.',reportChecks:['Executive-ready summary','Health Score and severity distribution','Estimated Loss and Potential Saving','Prioritized actions and next steps'],dashboardEyebrow:'Dashboard Preview',dashboardTitle:'One central view of health, risk, and progress.',dashboardLead:'Overview, Findings, and Monitoring work together so teams can see not only issues, but also their development and remediation status.',sample:'Representative product preview using sample data.'}}
function lang(){return document.documentElement.lang==='en'?'en':'de'}
function markup(t){return `<div id="lp6-product-proof">
<section class="lp6-section" id="findings"><div class="lp6-container"><div class="lp6-head"><p class="lp6-eyebrow">${t.findEyebrow}</p><h2>${t.findTitle}</h2><p>${t.findLead}</p></div><div class="lp6-findings-grid"><div class="lp6-findings-list"><div class="lp6-finding-item active"><span class="lp6-dot critical"></span><div><strong>${t.detailTitle}</strong><small>12 records · FIN-014</small></div><span class="lp6-loss">€18,400</span></div><div class="lp6-finding-item"><span class="lp6-dot high"></span><div><strong>Customers without payment terms</strong><small>43 records · SAL-009</small></div><span class="lp6-loss">€7,250</span></div><div class="lp6-finding-item"><span class="lp6-dot medium"></span><div><strong>Inactive items in open documents</strong><small>28 records · INV-021</small></div><span class="lp6-loss">€4,760</span></div></div><article class="lp6-finding-detail"><div class="lp6-detail-top"><span class="lp6-badge">Critical</span><span class="lp6-code">FIN-014</span></div><h3>${t.detailTitle}</h3><p>${t.detailText}</p><div class="lp6-detail-grid"><div class="lp6-detail-card"><span>${t.affected}</span><strong>12</strong></div><div class="lp6-detail-card"><span>${t.impact}</span><strong>€18,400</strong></div><div class="lp6-detail-card"><span>${t.status}</span><strong>${t.open}</strong></div></div><div class="lp6-recommendation"><strong>${t.recommend}</strong><p>${t.recommendText}</p></div><a class="lp6-method-link" href="loss-examples.html">${t.method}</a></article></div></div></section>
<section class="lp6-section dark" id="report"><div class="lp6-container lp6-report-grid"><div class="lp6-report-stage"><div class="lp6-page back"><span class="lp6-report-kicker">BCSENTINEL</span><h3 class="lp6-report-title">Findings & Next Steps</h3><div class="lp6-report-bars"><span></span><span></span><span></span></div></div><div class="lp6-page front"><span class="lp6-report-kicker">EXECUTIVE REPORT</span><h3 class="lp6-report-title">Data Health Assessment</h3><div class="lp6-report-score">72</div><div class="lp6-report-kpis"><div><span>Estimated Loss</span><strong>€48,300</strong></div><div><span>Potential Saving</span><strong>€31,700</strong></div><div><span>Findings</span><strong>37</strong></div><div><span>Critical</span><strong>8</strong></div></div><div class="lp6-report-bars"><span></span><span></span><span></span></div></div></div><div class="lp6-report-copy"><div class="lp6-head lp6-dark-head"><p class="lp6-eyebrow">${t.reportEyebrow}</p><h2>${t.reportTitle}</h2><p>${t.reportLead}</p></div><div class="lp6-checks">${t.reportChecks.map(x=>`<span>${x}</span>`).join('')}</div></div></div></section>
<section class="lp6-section alt" id="dashboard"><div class="lp6-container"><div class="lp6-head"><p class="lp6-eyebrow">${t.dashboardEyebrow}</p><h2>${t.dashboardTitle}</h2><p>${t.dashboardLead}</p></div><div class="lp6-dashboard-shell"><div class="lp6-dashboard-top"><strong>BCSentinel</strong><div class="lp6-dashboard-tabs"><span class="active">Overview</span><span>Findings</span><span>Monitoring</span></div></div><div class="lp6-dashboard-body"><aside class="lp6-sidebar"><strong>Data Health</strong><span class="active">Overview</span><span>Findings</span><span>Actions</span><span>Monitoring</span><span>Reports</span></aside><div class="lp6-dashboard-main"><div class="lp6-kpi-grid"><div class="lp6-kpi-card"><span>Health Score</span><strong>72 / 100</strong></div><div class="lp6-kpi-card"><span>Estimated Loss</span><strong>€48,300</strong></div><div class="lp6-kpi-card"><span>Potential Saving</span><strong>€31,700</strong></div><div class="lp6-kpi-card"><span>Open Findings</span><strong>37</strong></div></div><div class="lp6-dashboard-lower"><div class="lp6-panel"><h3>Module Health</h3><div class="lp6-mini-bars"><span></span><span></span><span></span><span></span></div></div><div class="lp6-panel"><h3>Priority Findings</h3><div class="lp6-mini-list"><div><span>Vendor bank accounts</span><strong>Critical</strong></div><div><span>Payment terms</span><strong>High</strong></div><div><span>Open documents</span><strong>Medium</strong></div></div></div></div></div></div></div><p class="lp6-caption">${t.sample}</p></div></section>
</div>`}
function loadStyles(){if(document.querySelector('link[data-lp6-proof]'))return;const l=document.createElement('link');l.rel='stylesheet';l.href='css/product-proof.css';l.dataset.lp6Proof='true';document.head.appendChild(l)}
function loadPricing(){if(document.querySelector('script[data-lp7-pricing]'))return;const s=document.createElement('script');s.src='js/pricing-conversion-journey.js';s.defer=true;s.dataset.lp7Pricing='true';document.body.appendChild(s)}
function render(){if(!/\/(?:index\.html)?$/.test(location.pathname))return;const story=document.getElementById('lp5-product-story');const pricing=document.getElementById('pricing');if(!story||!pricing)return;document.getElementById('lp6-product-proof')?.remove();pricing.insertAdjacentHTML('beforebegin',markup(copy[lang()]));}
function init(){loadStyles();render();loadPricing();setTimeout(render,220);setTimeout(render,800);new MutationObserver(m=>{if(m.some(x=>x.attributeName==='lang'))render()}).observe(document.documentElement,{attributes:true,attributeFilter:['lang']})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();