"""Read-only source audit; outputs QA evidence, never connects to BC or a database."""
from __future__ import annotations

import argparse
import hashlib
import json
import re
from collections import Counter
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
RUNNER = Path('bc-extension/app/src/codeunits/DHDeepScanRunner.Codeunit.al')
SCENARIOS = ('CUSTOMERS_MISSING_EMAIL', 'VENDORS_MISSING_PHONE',
             'ITEMS_WITHOUT_UNIT_PRICE', 'ITEMS_WITHOUT_UNIT_COST')


def reconstruct(customers=6000, vendors=2000, items=12000, seed=5001, rate=10):
    counts = dict.fromkeys(SCENARIOS, 0)
    for entity, target in enumerate((customers, vendors, items)):
        for sequence in range(1, target + 1):
            if ((sequence % 100) * 37 + seed % 100) % 100 < rate:
                scenario = entity if entity < 2 else 2 + ((sequence - 1) // 100) % 2
                counts[SCENARIOS[scenario]] += 1
    return counts


def procedures(source):
    matches = list(re.finditer(r'^    (?:local )?procedure (\w+)\(', source, re.M))
    return [(m[1], source.count('\n', 0, m.start()) + 1,
             source[m.start():matches[i + 1].start() if i + 1 < len(matches) else len(source)])
            for i, m in enumerate(matches)]


def catalog(source):
    rows, discrepancies = [], []
    pattern = r"AddCountFinding\(DeepScanRun, Score, IssuesCount, '([^']+)', '([^']+)', '([^']+)', (\w+), (\d+)\);"
    for name, start, block in procedures(source):
        matches = list(re.finditer(pattern, block))
        for m in matches:
            category, code, severity, counter, penalty = m.groups()
            # Preserve the actual source, including surrounding filters, in the appendix.
            conditions = re.findall(r'if ([^\n]+) then\s+' + counter + r' \+= 1;', block)
            assignments = re.findall(r'^\s*' + counter + r' := ([^\n]+);', block, re.M)
            rows.append(dict(code=code, category=category, severity=severity,
                             counter=counter, initial_penalty=int(penalty), procedure=name,
                             line=start + block.count('\n', 0, m.start()),
                             condition=conditions or assignments, aggregation='count'))
        if name.startswith('Run') and 'Duplicate' in name:
            m = re.search(r"IsCheckEnabled\('([^']+)'\)", block)
            if m:
                rows.append(dict(code=m[1], category='CUSTOMER' if 'Customer' in name else 'VENDOR',
                                 severity='high', counter='DuplicateCount', initial_penalty=8,
                                 procedure=name, line=start, condition=['DuplicateCount > 1; see full procedure'],
                                 aggregation='duplicate_group_or_repeated_group'))
        declared = re.search(r'ChecksCount \+= (\d+);', block)
        if matches and declared and int(declared[1]) != len(matches):
            discrepancies.append(dict(procedure=name, declared=int(declared[1]), actual=len(matches)))
    return rows, discrepancies


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--json-out', type=Path, required=True)
    parser.add_argument('--catalog-out', type=Path, required=True)
    args = parser.parse_args()
    source = (ROOT / RUNNER).read_text(encoding='utf-8')
    rows, discrepancies = catalog(source)
    evidence = dict(evidence_kind='STATIC_SOURCE_AUDIT_NOT_BC_RUNTIME',
                    runner_sha256=hashlib.sha256(source.encode()).hexdigest(),
                    scenario_counts=reconstruct(), check_count=len(rows),
                    category_counts=dict(Counter(r['category'] for r in rows)),
                    check_counter_discrepancies=discrepancies, checks=rows,
                    benchmark=dict(user_reported_seconds=502.226,
                                   business_records_per_second=20000 / 502.226,
                                   seconds_per_1000_business_records=502.226 / 20))
    args.json_out.parent.mkdir(parents=True, exist_ok=True)
    args.json_out.write_text(json.dumps(evidence, indent=2) + '\n', encoding='utf-8')
    lines = ['# EXT-50-12C — Product Check Catalog', '',
             'Generated by `scripts/audit_ext_50_12c.py` from the current AL source. Static evidence only.',
             'All 199 checks are included, including checks outside the generated master-data workload.',
             'Stable check ID is the AL finding title; localized names come from the check catalog.',
             'Category → module: CUSTOMER/VENDOR/LEDGER/FINANCE → Finance; ITEM/INVENTORY → Inventory;',
             'PURCHASE → Purchasing; JOB → Projects; other categories retain their names.', '',
             'For each row, the linked procedure below supplies the exact table declarations, filters,',
             'conditions and counter increments, including nested guards. No condition is inferred from a name.',
             'Count checks emit one finding only when enabled and count > 0. Duplicate checks differ:',
             'email emits groups; VAT/name deduplication has the marker defect documented in the main audit.',
             'All counts are company-wide after per-check filters/exceptions, never generator-run scoped.',
             'Severity may escalate in ResolveImpactSeverity. Initial penalty is superseded by recalculation:',
             'severity 1/3/6/10 + affected-count tier 1/2/4/6/8, summed per module;',
             'module score = 100 - floor(100P/(P+40)). Impact is backend count × minutes/60 × probability',
             '× annual frequency × hourly rate, rounded per finding, then summed. See main report for details.', '',
             '| Check ID / AL name | Category | Base severity | Counter | Initial penalty | Actual AL procedure |',
             '|---|---|---|---|---:|---|']
    for row in rows:
        lines.append(f"| {row['code']} | {row['category']} | {row['severity']} | {row['counter']} | {row['initial_penalty']} | [{row['procedure']}](#{row['procedure'].lower()}) (L{row['line']}) |")
    lines += ['', '## Exact table/filter/condition evidence', '',
              f'Source: `{RUNNER.as_posix()}`. Line references apply to audited HEAD 89faeb7.',
              'The following verbatim procedure slices make every counter traceable; they are evidence, not a replacement implementation.']
    names = {r['procedure'] for r in rows}
    names.update(('CountCustomersByEmail', 'CountVendorsByEmail', 'CountCustomersByVat',
                  'CountVendorsByVat', 'CountCustomersByNamePostCity', 'CountVendorsByNamePostCity',
                  'FindingExists', 'InsertFinding', 'AddCountFinding', 'ResolveImpactSeverity',
                  'GetLastItemMovementDate'))
    for name, start, block in procedures(source):
        if name in names:
            lines += ['', f'## {name}', '', f'Source line {start}.', '', '```al', block.rstrip(), '```']
    args.catalog_out.parent.mkdir(parents=True, exist_ok=True)
    args.catalog_out.write_text('\n'.join(lines) + '\n', encoding='utf-8')
    print(json.dumps({k: evidence[k] for k in ('scenario_counts', 'check_count', 'check_counter_discrepancies')}))


if __name__ == '__main__':
    main()
